### ISSUE TITLE
Images not loaded if you go through the catalog pagination 

### ISSUE THREAD

**Issue by pietervanuhm** [magepal/magento2-cataloglazyload#11]
#### Expected behavior: 
Images are loaded if you paginate through the catalog

#### Actual behavior: 
Images are NOT loaded if you paginate through the catalog, it only shows the first 8 products, this amount is set in the module configuration.

#### Steps to reproduce:
1. Go to this page: https://www.hairworldshop.nl/haar.html
2. Then click at the bottom to go to page 2. url: (https://www.hairworldshop.nl/haar.html?p=2)

#### Preconditions
The pagination is loaded by AJAX i think this is related, because if you refresh the page https://www.hairworldshop.nl/haar.html?p=2 then it is working.

BTW, i disabled now the module.

![screencapture-hairworldshop-nl-haar-html-2019-03-01-15_32_14](https://user-images.githubusercontent.com/4670666/53645229-b7bd9180-3c38-11e9-870c-a15a45b782bb.png)

**Comment by pietervanuhm** [comment]
BTW, i disabled now the module.

![screencapture-hairworldshop-nl-haar-html-2019-03-01-15_32_14](https://user-images.githubusercontent.com/4670666/53645229-b7bd9180-3c38-11e9-870c-a15a45b782bb.png)

**Comment by srenon** [comment]
Since AJAX pagination is not a native Magento feature, it next to impossible to support in our extension.

However, this feature should be easy to add.

Review your AJAX pagination code and find a suitable place after the content is loaded   (using JS Mix-in, jQuery events, or their API etc) and add something like

      $("img.lazy.swatch-option-loading").lazyload();

**Comment by pietervanuhm** [comment]
Hi Renon,

I will try that next week, thanks!

Gr. Pieter van Uhm
