### ISSUE TITLE
Can't setup:upgrade

### ISSUE THREAD

**Issue by gondas33** [magepal/magento2-cataloglazyload#12]
#### Steps to reproduce:
composer install magepal/magento2-cataloglazyload
bin/magento setup:upgrade
#### Preconditions

Latest version 2.3.2
Litespeed

system.log:
```[2019-09-17 14:17:47] main.ERROR: Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
MagePal_CatalogLazyLoad schema: current version - none, required version - 1.4.2
MagePal_CatalogLazyLoad data: current version - none, required version - 1.4.2 [] []
[2019-09-17 14:17:50] main.ERROR: Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
MagePal_CatalogLazyLoad schema: current version - none, required version - 1.4.2
MagePal_CatalogLazyLoad data: current version - none, required version - 1.4.2 [] []
[2019-09-17 14:17:56] main.ERROR: Please upgrade your database: Run "bin/magento setup:upgrade" from the Magento root directory.
The following modules are outdated:
MagePal_CatalogLazyLoad schema: current version - none, required version - 1.4.2
MagePal_CatalogLazyLoad data: current version - none, required version - 1.4.2 [] []
```

**Comment by srenon** [comment]
@an4rei ... this is not an issue with the extension... you are using the wrong command https://stackoverflow.com/a/33052263/1191288 

> composer update magepal/magento2-cataloglazyload

**Comment by gondas33** [comment]
@srenon I made the issue on the go. I mistakenly wrote install instead of require. If I would have written install I wouldn't be getting 
```
MagePal_CatalogLazyLoad schema: current version - none, required version - 1.4.2
MagePal_CatalogLazyLoad data: current version - none, required version - 1.4.2 [] []
```

would I?
Thanks!

**Comment by srenon** [comment]
The issue is still not related to this module.

You need to get composer v1.6.3 ... https://github.com/magepal/magento2-catalog-lazy-load/releases

You can try to delete the entry in "setup_module". see https://magento.stackexchange.com/questions/93194/magento-2-module-install-error-data-current-version-none-required-version-2
