### ISSUE TITLE
Issue after updating to 2.3.3

### ISSUE THREAD

**Issue by gondas33** [magepal/magento2-cataloglazyload#14]
#### Actual behavior: only 4 images are being loaded(using the 'ignore first x photos' settings)

```
<img class="lazy product-image-photo" data-original&#x3d;&quot;https&#x3a;&#x2f;&#x2f;avasting.ro&#x2f;pub&#x2f;media&#x2f;catalog&#x2f;product&#x2f;cache&#x2f;5098fac7f63ab917ed5a467c62445137&#x2f;1&#x2f;4&#x2f;14799__cutie-cu-geam-cheder-si-yala-minibox-500x500x150-mm_1.jpg&quot;="" src="" max-width="208" max-height="260" alt="Cutie hidrant interior minibox 500X500X140 avizata CE">
```

the above doesnt render a picture, this is the output in the frontend of the lazy-loaded images.

#### Preconditions

Update from 2.3.2 to 2.3.3
PHP version 7.3

**Comment by srenon** [comment]
@an4rei ... I'll add a fix for this shortly

**Comment by srenon** [comment]
@an4rei ... let me know if you still having issues with v1.7.0
