### ISSUE TITLE
The extension idles image loading

### ISSUE THREAD

**Issue by gediminaskv** [magepal/magento2-cataloglazyload#4]
Sometimes the extension idles image loading. A page loads, but images show loading gif. Just after several seconds it completes.

I've got error in system.log:
`main.CRITICAL: Class Magepal\CatalogLazyLoad\Helper\Data does not exist [] []`

and sometimes (don't know if it is connected with LazyLoad):
`main.CRITICAL: Warning: ltrim() expects parameter 1 to be string, object given in /home/[domain]/public_html/vendor/magento/framework/Code/Generator/EntityAbstract.php on line 152 [] []`

**Comment by srenon** [comment]
@gediminaskv ... what version of Magento 2.x are you using?

**Comment by gediminaskv** [comment]
2.1.8

**Comment by srenon** [comment]
Please upgrade to the new version release this morning which should fix "main.CRITICAL: Class Magepal\CatalogLazyLoad\Helper\Data does not exist"

**Comment by MidnightDesign** [comment]
#2 fixed this.

**Comment by srenon** [comment]
@gediminaskv ... are you still having issues?
