### ISSUE TITLE
Not working on Porto theme

### ISSUE THREAD

**Issue by ghost** [magepal/magento2-cataloglazyload#5]
I have successfully tested the module on Magento/Luma; we are using Porto theme at the moment, but as shown by the Dev Console, images are loading immediately. Do we need to tweak anything to make the module work (CSS classes, etc.)?

Thanks in advance!

**Comment by srenon** [comment]
@alen12345 ... Unfortunate I don't have access to that theme

**Comment by ghost** [comment]
@srenon I hope to have time in the near future to look into this and report back since the theme seems to be rather used in the community.

If I progress on anything, I will update you!

For now I think I can close the issue because it only affects this particular setup.

**Comment by srenon** [comment]
What is the demo URL for your theme?

**Comment by ghost** [comment]
https://themeforest.net/item/porto-ultimate-responsive-magento-theme/9725864

**Comment by srenon** [comment]
Each demo is slightly different, so which exact demo number?

**Comment by ghost** [comment]
They just differ for some css and block positions; anyhow this is the one I am using and that we can test:

http://www.portotheme.com/magento2/porto/demo8_en
